### ISSUE TITLE
Documentation step error during challenge creation on chalab

### ISSUE THREAD

**Issue by warrenpons** [codalab/chalab#106]
During the challenge creation on Chalab, we had a problem in the 7-th step (i.e Documentation) which it can be see in the following image. It's not a critical error because we could build the challenge bundle but, the bundle is not accepted by codalab due to an "overview" error (details can be seen in the following image too). However, we don't know if these errors are correlated.

![chalab](https://user-images.githubusercontent.com/33642171/33441970-4202b624-d5f4-11e7-9f85-ffe43abc9fa9.png)

![codalab](https://user-images.githubusercontent.com/33642171/33441973-43249ebe-d5f4-11e7-979a-84f7652c43b1.png)

**Comment by Tthomas63** [comment]
Hello, 

Thanks for bringing this issue up. Before the issue occurred had you edited default pages, or names at all? 

It looks like the issue is caused by not having one of the default pages named `overview`

Thanks,

**Comment by madclam** [comment]
Yes, we need to forbid changing the page names for the Codalab mandatory pages. The HTML files can have any names, but not the YAML tags. I modified the entries in the YAML file and now it works:
html:
  data: Data.html
  evaluation: Evaluation.html
  overview: Description.html
  terms: Terms.html

I had to fix another thing: the file "model.py" was uploaded instead of Starting_zit.zip.
We should implement a check that a zipfile is uploaded.
