### ISSUE TITLE
Dataset name inconsistent

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#82]
I created a challenge with https://chalab.lri.fr/wizard/.
This is https://chalab.lri.fr/wizard/challenges/39
The name of the challenge is iris and the dataset name should be iris. However, the input data ended up having dataset names:
"new dataset"
why?

**Comment by Tthomas63** [comment]
This was an issue with sept-staging datasets. I believe this should no longer be an issue on the current version. I created an Iris challenge template for the new group M2AIC2018 that shows that. It is strange because it says the name is Iris, but in the bundle it is called "new dataset".
![image](https://user-images.githubusercontent.com/7594063/31982718-e281aa7c-b90e-11e7-9fe5-c7179360b090.png)
