### ISSUE TITLE
Duplicate "saved" datasets

### ISSUE THREAD

**Issue by madclam** [codalab/chalab#92]
When you create your own datasets, they are save for later use, but there is no way to distinguish from datasets with the same name. Keep only the last one.

![image](https://user-images.githubusercontent.com/7594063/32080342-ecedaad2-ba63-11e7-8e8b-e4f631b484e0.png)

**Comment by Tthomas63** [comment]
Metrics also seem to have this issue.

**Comment by Tthomas63** [comment]
@madclam This has been pushed to : https://chalab-pr-99.herokuapp.com/wizard/

### Testing:

Create Two New Empty Competitions:

- On the first one, upload a dataset and confirm that data is marked `complete`

- Goto `choose another`, then on the dataset pick screen, choose `create` and upload the same dataset file.

<img width="567" alt="screen shot 2017-11-09 at 2 35 51 pm" src="https://user-images.githubusercontent.com/28552312/32633318-e5b90e48-c55b-11e7-98b6-819fb751f658.png">

<img width="363" alt="screen shot 2017-11-09 at 2 35 57 pm" src="https://user-images.githubusercontent.com/28552312/32633296-ce9f26fc-c55b-11e7-8f75-f2a8ef84a35c.png">

- You should be taken to a duplicate dataset page, and since we do not have a competition referencing this dataset, we should just be able to delete/overwrite it. 

<img width="1091" alt="screen shot 2017-11-09 at 2 37 03 pm" src="https://user-images.githubusercontent.com/28552312/32633379-1e5f0fea-c55c-11e7-8a8f-d8913abdd8d2.png">

- Goto the next competition once the above is completed succesfully

- On the data page, create a new dataset again with the same file. You should end up on the duplicate datasets page, however now you should only have the option to re-name your current dataset. The `duplicate` should be referenced by the other competition so we should not be able to overwrite it. 

<img width="1096" alt="screen shot 2017-11-09 at 2 38 59 pm" src="https://user-images.githubusercontent.com/28552312/32633356-094c1d78-c55c-11e7-9833-80d8215f8d12.png">

- Instead of entering a name, and clicking the re-name button, please click `Data` on the breadcrumb navigation above the main content. 

- Click `choose another`, and create another dataset, once again with the same file. This time the duplicate dataset page should give you an option to re-name your current dataset, or have the un-used/un-referenced deleted/overwritten. 

<img width="1091" alt="screen shot 2017-11-09 at 2 37 03 pm" src="https://user-images.githubusercontent.com/28552312/32633403-3dd2fa26-c55c-11e7-8e67-941fdd617d4f.png">

-----
If all have these cases can be met successfully, I believe that would be the basis for the correct behavior we would like, with tweaks as necessary. 

I will continue to update this as I find issues and correct behavior.

**Comment by madclam** [comment]
I loaded a dataset with the same name twice in the SAME competition and ended up on this page:
![image](https://user-images.githubusercontent.com/7594063/32796076-77c4374e-c922-11e7-89a3-adc41d64ef40.png)

I had only the option "Overwrite" so I found this scary and confusing: I would not know what I should do without the danger of loosing data or how to cancel. What is the consequence of this action?
I think there should also be a "cancel" button, in case this was a mistake.

**Comment by madclam** [comment]
In the same test, I tried to continue and create a bundle, but I got an error:
![image](https://user-images.githubusercontent.com/7594063/32804668-89e43a04-c93c-11e7-9428-651c0b01f349.png)
I cannot add the metric, so I cannot finish the test of https://chalab-pr-99.herokuapp.com/wizard/challenges/4

**Comment by Tthomas63** [comment]
The metric error is from Heroku not supporting local storage. 

Since Heroku is not meeting our needs as staging/test solution I have created an AWS S3 EC2 at:

http://ec2-34-209-195-171.us-west-2.compute.amazonaws.com/

It also has a static ip of: [34.209.195.171](34.209.195.171)

It is currently on the duplicate datasets branch discussed in this issue and is working when running completely thought the basic test.

In regards to your first reply, I can also certainly add a `cancel` button. What should the behavior for this be though? Redirect back to the new dataset page without actually saving the dataset?

**Comment by Tthomas63** [comment]
Ask for dataset name before upload, require or default to zip name?

**Comment by madclam** [comment]
1) Add field to ask for dataset description (short, optional) at the time of dataset zipfile upload =>DataDescription.
2) Upload the zip file. Get the name of the dataset from the files in the zipfile => DataName.
  - DataUniqueID = name showing in the menus => [DataName DataDescription num]
  - num = order number of datasets with same DataName

All the rest is the same as before: the name of the dataset that will appear in the competition bundle remains the name of the files in the data zipfile.

**Comment by madclam** [comment]
To make it the same for metrics:
1) Use field of metric description (short, optional) =>MetricDescription.
2) Get MetricName
 - case 1: get it from the box of metric name when users supply code in the editor.
 - case 2: get it from uploaded file.
[like before, no change]
Create a unique metric ID:
MetricUniqueID = name showing in the menus => [MetricName MetricDescription num]
num = order number of metrics with same MetricName


![image](https://user-images.githubusercontent.com/7594063/32909660-fa9b262e-cabb-11e7-92c6-f46beec375de.png)

**Comment by ItsHalvy** [comment]
Debug description save issue.
- Description will save when updating without a file upload
- Description will not save when updating with a file upload
(Bug with WIP Code)

**Comment by Tthomas63** [comment]
- Change wording of optional description explanation.

- Remove no file chosen
